using System.Collections.Generic;

using Solar.FiestaLib.Data;

namespace Solar.Zone
{
    public sealed class ZoneData
    {
        public byte ID { get; set; }
        public List<MapInfo> MapsToLoad { get; set; }
        public ushort Port { get; set; } //we let this assign by worldserver
        public string IP { get; set; }
        public string EntityString { get; set; } //string to connect to DB (generated by world)
    }
}
